FROM ubuntu:15.04
MAINTAINER Will Jordan <will.jordan@gmail.com>

ADD *.sh /root/
WORKDIR /root
RUN chmod +x *.sh; sync;

ENV MOZJPEG_VERSION_MAJOR 3
ENV MOZJPEG_VERSION_MINOR 1
RUN ./mozjpeg.sh

ENV LIBVIPS_VERSION_MAJOR 8
ENV LIBVIPS_VERSION_MINOR 0
ENV LIBVIPS_VERSION_PATCH 2
RUN ./vips.sh
